### ISSUE TITLE
Styles are not applied to the expanded view

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#44]
1) Open AdTechMedia configuration page
2) Scroll down to the `Templates Management` -> `Overall Position and Styling`
3) Change colors in "Background Color" and "Footer Background Color" and click on [Save] button (attachment 1)
4) Make sure that ATM module is enabled and open any article
5) Click on [Arrow] expand button 

Expected result: expanded module view should be colored in the {Background Color}
Actual result: background is not colored in expanded view but only in collapsed (attachments 2&3). Bug reproduces for all styles: background, border, box shadow.

Note: styles are not applied in Templates Management as well (attachment 4)

Please refer to the attachments:
<img width="1222" alt="screen shot 2017-02-27 at 10 53 35 am" src="https://cloud.githubusercontent.com/assets/10956412/23354701/1b36d572-fcdb-11e6-9ba6-3cd4ad636f74.png">

<img width="1280" alt="screen shot 2017-02-27 at 10 53 56 am" src="https://cloud.githubusercontent.com/assets/10956412/23354706/1ffe1d40-fcdb-11e6-9bc7-586a7cf1dad3.png">

<img width="1280" alt="screen shot 2017-02-27 at 10 54 04 am" src="https://cloud.githubusercontent.com/assets/10956412/23354711/2451c568-fcdb-11e6-9a78-bdc7f0594054.png"> 

<img width="462" alt="screen shot 2017-02-27 at 10 58 51 am" src="https://cloud.githubusercontent.com/assets/10956412/23354892/df527704-fcdb-11e6-8673-980f6bf73fad.png">

**Comment by azzaromax** [comment]
fixed

**Comment by ghost** [comment]
Bug is still reproducing for the border styles. 

Please refer to the attachment: footer border is displayed but the main border isn't.
Note: reproduces both for expanded and collapsed views.

<img width="671" alt="screen shot 2017-03-03 at 10 54 49 am" src="https://cloud.githubusercontent.com/assets/10956412/23544476/dc549eac-ffff-11e6-9195-a3eb011edb99.png">

**Comment by avozicov** [comment]
Task is blocked for testing by following issue.
https://github.com/AdTechMedia/drupal-module/issues/54

**Comment by avozicov** [comment]
Task was tested only in "Config" page and test is passed.
_Note :_ 
Task will be retested at the "Content" page once the following blocking issue will be resolved 
https://github.com/AdTechMedia/drupal-module/issues/60
